[package]
name = "reply"
version = "0.0.0"
edition = "2021"
authors = ["Felipe S. S. Schneider <schneider.felipe.5@gmail.com>"]
description = "Convert any command-line application into a REPL"
homepage = "https://github.com/schneiderfelipe/answer/tree/main/reply"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
